// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("API.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("serial");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("varchar");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("varchar");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar");

                b.Property<int>("Phone")
                    .HasColumnType("int");

                b.Property<string>("Profession")
                    .IsRequired()
                    .HasColumnType("varchar");

                b.HasKey("Id");

                b.ToTable("Employees");
            });
        }
    }
}
